# Generated by Django 5.0.3 on 2024-05-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='catagory',
        ),
    ]
