# Generated by Django 5.0.3 on 2024-05-14 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='catagory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task.catagory'),
            preserve_default=False,
        ),
    ]
